name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.com/

      - name: Install dependencies
        run: |
          npm i -g pnpm
          pnpm install

      - name: Build
        run: |
          pnpm build:components

      - name: Create Release Pull Request
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        uses: changesets/action@v1
        with:
          working-directory: ./packages/components
          tagName: ${{ env.VERSION }}
          releaseName: '${{ env.VERSION }}'
          publish: pnpm ci:publish
